---
- name: Check if requested version is the default Node.js version
  ansible.builtin.shell: >
    set -o pipefail && \
    . ./nvm.sh && \
    nvm alias default --no-colors | grep '{{ nvm_node_version }}'
  args:
    executable: /bin/bash
    chdir: "{{ nvm_install_path }}"
  register: nvm_check_default
  changed_when: false
  failed_when: false

- name: Set default Node.js version to {{ nvm_node_version }}
  ansible.builtin.shell: ". ./nvm.sh && nvm alias default {{ nvm_node_version }}"
  args:
    chdir: "{{ nvm_install_path }}"
  when: nvm_check_default.rc != 0
